alfa-laboratory/ratauth

- docs/src/docs/api.adoc
- domain/src/main/java/ru/ratauth/interaction/InvalidateSessionRequest.java
- domain/src/main/java/ru/ratauth/services/SessionService.java
- server/src/main/groovy/ru/ratauth/server/handlers/SessionHandler.groovy
- server/src/main/groovy/ru/ratauth/server/handlers/TokenHandler.groovy
- server/src/main/groovy/ru/ratauth/server/handlers/readers/SessionRequestReader.groovy
- server/src/main/groovy/ru/ratauth/server/local/PersistenceServiceStubConfiguration.groovy
- server/src/test/groovy/ru/ratauth/server/handlers/SessionHandlerSpec.groovy
introducing session invalidation API
> session invalidation

- build.gradle
- domain/src/main/java/ru/ratauth/entities/Session.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
- server/src/test/groovy/ru/ratauth/entities/SessionTest.groovy
> FIX #18 return actual entry for some rp

- build.gradle
- server/build.gradle
- server/src/main/groovy/ru/ratauth/server/RatAuthApplication.groovy
- server/src/main/groovy/ru/ratauth/server/authcode/AuthCode.java
- server/src/main/groovy/ru/ratauth/server/authcode/AuthCodeJWTConverter.java
- server/src/main/groovy/ru/ratauth/server/authcode/AuthCodeProperties.java
- server/src/main/groovy/ru/ratauth/server/authcode/AuthCodeService.java
- server/src/main/groovy/ru/ratauth/server/authcode/AuthCodeServiceImpl.java
- server/src/main/groovy/ru/ratauth/server/jwt/HMAC256JWTSigner.java
- server/src/main/groovy/ru/ratauth/server/jwt/JWTConverter.java
- server/src/main/groovy/ru/ratauth/server/jwt/JWTProperties.java
- server/src/main/groovy/ru/ratauth/server/jwt/JWTSigner.java
- server/src/main/groovy/ru/ratauth/server/scope/Scope.java
- server/src/main/groovy/ru/ratauth/server/scope/ScopeProperties.java
- server/src/main/groovy/ru/ratauth/server/secutiry/MD5Generator.java
- server/src/main/groovy/ru/ratauth/server/secutiry/OAuthIssuer.java
- server/src/main/groovy/ru/ratauth/server/secutiry/OAuthIssuerImpl.java
- server/src/main/groovy/ru/ratauth/server/secutiry/UUIDValueGenerator.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdSessionService.java
- server/src/main/resources/application.yml
- server/src/test/groovy/ru/ratauth/server/BaseDocumentationSpec.groovy
- server/src/test/groovy/ru/ratauth/server/authcode/AuthCodeServiceTest.java
- server/src/test/groovy/ru/ratauth/server/authcode/ScopeTest.java
- server/src/test/groovy/ru/ratauth/server/jwt/HMAC256JWTSignerTest.java
- server/src/test/resources/application.yml
> PASSPORT-307 add auth_code as jwt

- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthTokenService.java
> added acr username

- domain/src/main/java/ru/ratauth/exception/AuthorizationException.java
> added new exception session closed -> 403

- domain/src/main/java/ru/ratauth/entities/OpenIdConnectDiscoveryProperties.java
- server/src/main/groovy/ru/ratauth/server/configuration/OpenIdConnectDefaultDiscoveryProperties.java
- server/src/main/groovy/ru/ratauth/server/handlers/WellKnownHandler.groovy
- server/src/main/resources/application-local.yml
- server/src/test/groovy/ru/ratauth/server/handlers/WellKnownHandlerSpec.groovy
- server/src/test/resources/application.yml
Добавлен временный параметр afp_endpoint
> Added temporary parameter for "not clients" - afp_endpoint

- domain/src/main/java/ru/ratauth/entities/DeviceInfo.java
- domain/src/main/java/ru/ratauth/interaction/AuthzRequest.java
- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollHandler.groovy
- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollRequest.java
- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollService.java
- server/src/main/groovy/ru/ratauth/server/handlers/readers/AuthzRequestReader.groovy
> add deviceUUID to DeviceInfo Entity

- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
add missing createDeviceInfoFromRequest method
> add deviceUUID to createDeviceInfoFromRequest()

- domain/src/main/java/ru/ratauth/interaction/AuthzResponse.java
- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollService.java
- server/src/main/groovy/ru/ratauth/server/extended/update/UpdateResponse.java
- server/src/main/groovy/ru/ratauth/server/local/PersistenceServiceStubConfiguration.groovy
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
> added update code response fields

- domain/src/main/java/ru/ratauth/services/SessionService.java
- server/src/main/groovy/ru/ratauth/server/local/PersistenceServiceStubConfiguration.groovy
> Provide whole session to API

- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
Refactoring the creation of authorization response to Observable
P.S. getUpdateCode method should return an empty Observable instead throwing an exception
> Refactoring the creation of authorization response to Observable

- server/src/main/groovy/ru/ratauth/server/handlers/readers/AuthzRequestReader.groovy
if device_ip empty then add x-forwarded-for header if it exists
> proceed x-forwarded-header to idp by field device_ip

- domain/src/main/java/ru/ratauth/interaction/AuthzResponseType.java
- server/src/main/groovy/ru/ratauth/server/services/AuthSessionService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthTokenService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdSessionService.java
- server/src/test/groovy/ru/ratauth/server/TokenAPISpec.groovy
Added flag to refresh time refreshToken to Entries
> update time refresh token to Entries

- build.gradle
- domain/src/main/java/ru/ratauth/exception/AuthorizationException.java
- ratauth-spring-boot-autoconfigure/src/test/java/ru/ratauth/RatAuthAutoConfigurationTest.java
- server/src/main/groovy/ru/ratauth/server/RatAuthApplication.groovy
- server/src/main/groovy/ru/ratauth/server/configuration/DestinationConfiguration.java
- server/src/main/groovy/ru/ratauth/server/configuration/HazelcastServiceConfiguration.java
- server/src/main/groovy/ru/ratauth/server/configuration/IdentityProviderConfiguration.java
- server/src/main/groovy/ru/ratauth/server/services/CachingService.java
- server/src/main/groovy/ru/ratauth/server/services/HazelcastCachingService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
- server/src/main/groovy/ru/ratauth/server/services/dto/CachingUserKey.java
- server/src/main/resources/application.yml
- server/src/test/groovy/ru/ratauth/server/AuthorizationAPIRestIdentityProviderSpec.groovy
- server/src/test/groovy/ru/ratauth/server/AuthorizationAPISpec.groovy
- server/src/test/resources/application.yml
Add Hazelcast client to cache auth attempt count
> Passport 2836

- domain/src/main/java/ru/ratauth/services/SessionService.java
- server/src/main/groovy/ru/ratauth/server/local/PersistenceServiceStubConfiguration.groovy
- server/src/main/groovy/ru/ratauth/server/services/OpenIdSessionService.java
Need if you using separate collection on check_token request
> Provide whole session to keep session data

- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollService.java
- server/src/main/groovy/ru/ratauth/server/extended/update/UpdateProcessResponse.java
Add username in UpdateProcessResponse to send it after second factor
> Add username in UpdateProcessResponse

- server/src/main/groovy/ru/ratauth/server/services/OpenIdSessionService.java
1.  Remove deprecated method calling
2. Remove doOnNext calling (moment of doOnNext call is unpredictable by spec)
> Refactoring

- domain/src/main/java/ru/ratauth/exception/AuthorizationException.java
- server/src/main/groovy/ru/ratauth/server/handlers/AuthorizationHandlers.groovy
- server/src/main/groovy/ru/ratauth/server/local/PersistenceServiceStubConfiguration.groovy
- server/src/main/groovy/ru/ratauth/server/services/AuthClientService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthTokenService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdClientService.java
- server/src/test/groovy/ru/ratauth/server/AuthorizationAPISpec.groovy
- server/src/test/groovy/ru/ratauth/server/RegistrationAPISpec.groovy
- server/src/test/groovy/ru/ratauth/server/TokenAPISpec.groovy
> Check rp status

- domain/src/main/java/ru/ratauth/entities/Session.java
- domain/src/main/java/ru/ratauth/entities/Token.java
- domain/src/main/java/ru/ratauth/entities/TokenLifeType.java
- domain/src/main/java/ru/ratauth/exception/ExpiredException.java
- server/src/main/groovy/ru/ratauth/server/services/AuthSessionService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdAuthorizeService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdSessionService.java
This reverts commit 1dbf3cd09b9a67a574c318afd4ea04ececee20bb.
TEMPORARY !!!!! REVERT!!! Return after introduction
> Revert "added tag token type"

- server/src/main/groovy/ru/ratauth/server/extended/enroll/verify/VerifyEnrollService.java
- server/src/main/groovy/ru/ratauth/server/services/OpenIdDeviceService.java
> Hystrix extra fix
